// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: messaging.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StringArrayService_SendStringArray_FullMethodName = "/io.debezium.server.iceberg.rpc.StringArrayService/SendStringArray"
)

// StringArrayServiceClient is the client API for StringArrayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service definition.
type StringArrayServiceClient interface {
	// Sends a string array and returns a simple response.
	SendStringArray(ctx context.Context, in *StringArrayRequest, opts ...grpc.CallOption) (*StringArrayResponse, error)
}

type stringArrayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStringArrayServiceClient(cc grpc.ClientConnInterface) StringArrayServiceClient {
	return &stringArrayServiceClient{cc}
}

func (c *stringArrayServiceClient) SendStringArray(ctx context.Context, in *StringArrayRequest, opts ...grpc.CallOption) (*StringArrayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringArrayResponse)
	err := c.cc.Invoke(ctx, StringArrayService_SendStringArray_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StringArrayServiceServer is the server API for StringArrayService service.
// All implementations must embed UnimplementedStringArrayServiceServer
// for forward compatibility.
//
// The service definition.
type StringArrayServiceServer interface {
	// Sends a string array and returns a simple response.
	SendStringArray(context.Context, *StringArrayRequest) (*StringArrayResponse, error)
	mustEmbedUnimplementedStringArrayServiceServer()
}

// UnimplementedStringArrayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStringArrayServiceServer struct{}

func (UnimplementedStringArrayServiceServer) SendStringArray(context.Context, *StringArrayRequest) (*StringArrayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendStringArray not implemented")
}
func (UnimplementedStringArrayServiceServer) mustEmbedUnimplementedStringArrayServiceServer() {}
func (UnimplementedStringArrayServiceServer) testEmbeddedByValue()                            {}

// UnsafeStringArrayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StringArrayServiceServer will
// result in compilation errors.
type UnsafeStringArrayServiceServer interface {
	mustEmbedUnimplementedStringArrayServiceServer()
}

func RegisterStringArrayServiceServer(s grpc.ServiceRegistrar, srv StringArrayServiceServer) {
	// If the following call pancis, it indicates UnimplementedStringArrayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StringArrayService_ServiceDesc, srv)
}

func _StringArrayService_SendStringArray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringArrayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringArrayServiceServer).SendStringArray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StringArrayService_SendStringArray_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringArrayServiceServer).SendStringArray(ctx, req.(*StringArrayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StringArrayService_ServiceDesc is the grpc.ServiceDesc for StringArrayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StringArrayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.debezium.server.iceberg.rpc.StringArrayService",
	HandlerType: (*StringArrayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendStringArray",
			Handler:    _StringArrayService_SendStringArray_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messaging.proto",
}
